import { Inter } from "next/font/google";
import "./globals.css";
import "../public/lib/bootstrap/css/bootstrap.min.css";
import "../public/lib/font-awesome/css/font-awesome.min.css";
import "../public/lib/animate/animate.min.css";
import "../public/lib/ionicons/css/ionicons.min.css";
import "../public/lib/owlcarousel/assets/owl.carousel.min.css";
import "../public/lib/lightbox/css/lightbox.min.css";
import "../public/css/style.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Bryan Bayoca Weekly Blogs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body id="page-top" className={inter.className}>{children}</body>
    </html>
  );
}
